-- Importar contactos de Beacons (95 personas que descargaron la guía)
-- Ejecutar esto en Supabase SQL Editor

INSERT INTO newsletter_subscribers (email, first_name, last_name, source, platform, date_added, imported_from) VALUES
('linetday001@gmail.com', 'Daysi', NULL, 'Store - Guía BASICA', 'Instagram', '2026-05-13', 'beacons'),
('wilmar.wiooo@gmail.com', 'Wilmar', NULL, 'Store - Guía BASICA', 'Beacons', '2026-05-13', 'beacons'),
('ldanielaco@gmail.com', 'Laura', NULL, 'Store - Guía BASICA', 'Instagram', '2026-05-12', 'beacons'),
('tetileh627@imashr.com', 'Teli', 'Haye', 'Store - Guía BASICA', 'Beacons', '2026-05-12', 'beacons'),
('tatiramz10@gmail.com', 'Tatiana', 'Ramrez', 'Store - Guía BASICA', 'Beacons', '2026-05-11', 'beacons'),
('ovejanegra763@gmail.com', 'Nelson', 'Fernando Jaimes Castillo', 'Store - Guía BASICA', 'Instagram', '2026-05-11', 'beacons'),
('capirucho11benitez@gmail.com', 'Edwin', 'Ortiz', 'Store - Guía BASICA', 'Instagram', '2026-05-11', 'beacons'),
('angelyquebella77@gmail.com', 'Benny', 'Yohana', 'Store - Guía BASICA', 'Instagram', '2026-05-09', 'beacons'),
('brauliopenamendez@me.com', 'Braulio', 'Pea', 'Store - Guía BASICA', 'Beacons', '2026-05-09', 'beacons'),
('key_kurono@hotmail.com', 'Alexander', 'Vargas', 'Store - Guía BASICA', 'Instagram', '2026-05-09', 'beacons'),
('stvenmendez2006@gmail.com', 'Xavier', 'Mndez', 'Store - Guía BASICA', 'Instagram', '2026-05-09', 'beacons'),
('mebv03@gmail.com', 'Madeleine', NULL, 'Store - Guía BASICA', 'Instagram', '2026-05-08', 'beacons'),
('juanchoo.hidalgo@gmail.com', 'Juancho', 'Hidalgo', 'Store - Guía BASICA', 'Beacons', '2026-05-08', 'beacons'),
('bpatino@uc.edu.co', 'Brayan', 'Patio', 'Store - Guía BASICA', 'Beacons', '2026-05-08', 'beacons'),
('hidalgobarriosyulieth@gmail.com', 'Brithney', NULL, 'Store - Guía BASICA', 'Instagram', '2026-05-07', 'beacons'),
('mairamartin07@gmail.com', 'Maira', 'Alejandra Martin Snchez', 'Store - Guía BASICA', 'Instagram', '2026-05-06', 'beacons'),
('leidyjoanarojas@gmail.com', 'Leidy', 'Rojas', 'Store - Guía BASICA', 'Beacons', '2026-05-05', 'beacons'),
('magdcomercial@gmail.com', 'Mateo', 'Gutirrez', 'Store - Guía BASICA', 'Instagram', '2026-05-02', 'beacons'),
('castillobeltranjhony@gmail.com', 'Jonh', NULL, 'Store - Guía BASICA', 'Beacons', '2026-05-02', 'beacons'),
('sofilagosb11@gmail.com', 'Sofa', 'Lagos', 'Store - Guía BASICA', 'Beacons', '2026-04-30', 'beacons'),
('juandiorjuela12@gmail.com', 'Juan', NULL, 'Store - Guía BASICA', 'Beacons', '2026-04-28', 'beacons'),
('kennethquinterorivera@gmail.com', 'Kenneth', 'Quintero', 'Store - Guía BASICA', 'Beacons', '2026-04-27', 'beacons'),
('danielasuarez0402@gmail.com', 'daniela', NULL, 'Store - Guía BASICA', 'Beacons', '2026-04-24', 'beacons'),
('valenz_95@hotmail.com', 'Valentina', NULL, 'Store - Guía BASICA', 'Beacons', '2026-04-22', 'beacons'),
('margievanegaslopez@gmail.com', 'Margie', NULL, 'Store - Guía BASICA', 'Beacons', '2026-04-20', 'beacons'),
('nathasqvarela@gmail.com', 'Nathalia', NULL, 'Store - Guía BASICA', 'Beacons', '2026-04-19', 'beacons'),
('gustavo.restrepo29@gmail.com', 'Gustavo', NULL, 'Store - Guía BASICA', 'Beacons', '2026-04-18', 'beacons'),
('haguilar1981@gmail.com', 'Hilda', NULL, 'Store - Guía BASICA', 'Beacons', '2026-04-18', 'beacons'),
('dmirandacardenas@gmail.com', 'Dylan', 'Miranda', 'Store - Guía BASICA', 'Beacons', '2026-04-14', 'beacons'),
('santiagogonzalezc2000@gmail.com', 'Santiago', 'Gonzlez', 'Store - Guía BASICA', 'Beacons', '2026-04-13', 'beacons'),
('nicod7parra@gmail.com', 'Nicolas', NULL, 'Store - Guía BASICA', 'Beacons', '2026-04-12', 'beacons'),
('zunigajh100@gmail.com', 'Jhon', NULL, 'Store - Guía BASICA', 'TikTok', '2026-04-09', 'beacons'),
('jahirferrer54@gmail.com', 'Jahir', 'Ferrer', 'Store - Guía BASICA', 'Beacons', '2026-04-09', 'beacons'),
('luisorojas2020.l@gmail.com', 'Luis', 'rojas', 'Store - Guía BASICA', 'Beacons', '2026-04-08', 'beacons'),
('sandymora717@gmail.com', 'Sandy', 'Mora', 'Store - Guía BASICA', 'TikTok', '2026-04-07', 'beacons'),
('saeromero04@gmail.com', 'Samuel', NULL, 'Store - Guía BASICA', 'TikTok', '2026-04-06', 'beacons'),
('ciges90851@flownue.com', 'Alex', NULL, 'Store - Guía BASICA', 'Beacons', '2026-04-05', 'beacons'),
('canontejadajoel@gmail.com', 'Joel', NULL, 'Store - Guía BASICA', 'Beacons', '2026-03-31', 'beacons'),
('mateoparra1904@gmail.com', 'David', NULL, 'Store - Guía BASICA', 'TikTok', '2026-03-27', 'beacons'),
('luciengauttier8@gmail.com', 'Lucien', NULL, 'Store - Guía BASICA', 'Beacons', '2026-03-24', 'beacons'),
('michellhoyos@gmail.com', 'Michelle', 'Hoyos', 'Store - Guía BASICA', 'Beacons', '2026-03-24', 'beacons'),
('reimon.morillo@icloud.com', 'Reimon', 'Morillo', 'Store - Guía BASICA', 'Beacons', '2026-03-23', 'beacons'),
('nandohersheys@gmail.com', 'Fernando', NULL, 'Store - Guía BASICA', 'Beacons', '2026-03-22', 'beacons'),
('karolinebarrera73@gmail.com', 'Karoline', NULL, 'Store - Guía BASICA', 'Beacons', '2026-03-20', 'beacons'),
('fabio_cuadros@hotmail.com', 'Fabio', NULL, 'Store - Guía BASICA', 'Beacons', '2026-03-19', 'beacons'),
('auricel.ugc@gmail.com', 'Auricel', NULL, 'Store - Guía BASICA', 'Beacons', '2026-03-19', 'beacons'),
('auricelugo@gmail.com', 'Auricel', NULL, 'Store - Guía BASICA', 'Beacons', '2026-03-19', 'beacons'),
('miguelangelcabreragaray@gmail.com', 'Miguel', NULL, 'Store - Guía BASICA', 'Beacons', '2026-03-19', 'beacons'),
('herediacorrea0@gmail.com', 'Santiago', 'Heredia', 'Store - Guía BASICA', 'Beacons', '2026-03-18', 'beacons'),
('lesstertalis@gmail.com', 'Gustavo', NULL, 'Store - Guía BASICA', 'Beacons', '2026-03-17', 'beacons'),
('rodriguezdilan35@gmail.com', 'Dylan', 'Rodriguez', 'Store - Guía BASICA', 'TikTok', '2026-03-17', 'beacons'),
('danielgarciatablaza@gmail.com', 'Daniel', 'Garca', 'Store - Guía BASICA', 'Beacons', '2026-03-17', 'beacons'),
('erikapcb23@gmail.com', 'Erika', NULL, 'Store - Guía BASICA', 'Beacons', '2026-03-16', 'beacons'),
('afvalerianomartinez23@gmail.com', 'Andrs', 'Felipe', 'Store - Guía BASICA', 'Beacons', '2026-03-14', 'beacons'),
('allanojp@gmail.com', 'Allan', 'Olivares', 'Store - Guía BASICA', 'TikTok', '2026-02-25', 'beacons'),
('eltatangarcia@gmail.com', 'Jhonatan', 'garcia', 'home - Email & SMS', 'TikTok', '2026-02-10', 'beacons'),
('diego98madero@gmail.com', 'diego', 'madero', 'Store - Guía BASICA', 'Beacons', '2025-04-16', 'beacons'),
('launaranjo59@gmail.com', 'Laura', NULL, 'Store - Guía BASICA', 'TikTok', '2025-04-07', 'beacons'),
('kenigar2@gmail.com', 'Kenigar2gmailcom', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-16', 'beacons'),
('cidnusiness07@gmail.com', 'Albert', 'cid', 'Store - Guía BASICA', 'TikTok', '2025-03-13', 'beacons'),
('jhesuafelipe@hotmail.com', 'Jesus', 'sepulveda', 'Store - Guía BASICA', 'TikTok', '2025-03-13', 'beacons'),
('cesarandresps3@gmail.com', 'Cesar', 'Acevedo', 'Store - Guía BASICA', 'TikTok', '2025-03-13', 'beacons'),
('davidvivas22@hotmail.com', 'David', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-13', 'beacons'),
('miguelangellara@hotmail.com', 'Miguel', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-13', 'beacons'),
('gissel.nm0205@gmail.com', 'Gisse', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-13', 'beacons'),
('tropo.ayunos-1j@icloud.com', 'Johnatan', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-13', 'beacons'),
('wm141996@gmail.com', 'William', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-13', 'beacons'),
('sebata10@hotmail.com', 'Sebastin', 'Tapias Tovar', 'Store - Guía BASICA', 'TikTok', '2025-03-13', 'beacons'),
('antoniobohorquez462@gmail.com', 'Antonio', 'B', 'Store - Guía BASICA', 'TikTok', '2025-03-12', 'beacons'),
('fer-1470@hotmail.com', 'Mara', 'Fernanda', 'Store - Guía BASICA', 'TikTok', '2025-03-12', 'beacons'),
('romaomar@icloud.com', 'Omar', 'Acua', 'Store - Guía BASICA', 'Beacons', '2025-03-12', 'beacons'),
('riverside041000@gmail.com', 'Alexis', 'Rojas', 'Store - Guía BASICA', 'TikTok', '2025-03-12', 'beacons'),
('mariaceballos734@gmail.com', 'Maria', 'jose ceballos', 'Store - Guía BASICA', 'TikTok', '2025-03-12', 'beacons'),
('xdcamilo01@gmail.com', 'Camiloxi19', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-12', 'beacons'),
('mateocastillo64@gmail.com', 'Mateo', 'Castillo', 'Store - Guía BASICA', 'TikTok', '2025-03-12', 'beacons'),
('sebastian.velezm96@gmail.com', 'Sebastian', 'Velez', 'Store - Guía BASICA', 'TikTok', '2025-03-12', 'beacons'),
('fa.gallegos22@gmail.com', 'Andres', 'gallegos', 'Store - Guía BASICA', 'TikTok', '2025-03-12', 'beacons'),
('cranial-organic8l@icloud.com', 'Ed', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('sofievillaj@gmail.com', 'Sofia', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('p3210801@gmail.com', 'John', 'doe', 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('sortizm23@gmail.com', 'Esteban', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('pinerosmorakaren@gmail.com', 'Karen', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('escotabgroup@gmail.com', 'Jenifer', 'Gonzlez', 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('flotantivo@gmail.com', 'Flotantivo', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('barbarannicolas@gmail.com', 'Nicolas', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('jhon96.26@hotmail.com', 'Jhon', 'guerrero', 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('deivyluna14@gmail.com', 'David', 'Luna', 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('jesuspk1997@gmail.com', 'Jess', 'g', 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('maferendon2010@hotmail.com', 'Mara', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('torrescano.je@gmail.com', 'Juanes', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('enriqueportillo2019@gmail.com', 'Leonardo', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('sanjuan_96@hotmail.es', 'Daniel', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('valentincontreras209@gmail.com', 'Valentin', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('origomezcordoba2003@gmail.com', 'Oriana', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-11', 'beacons'),
('cristiangiron84@gmail.com', 'Christian', 'Giron', 'Store - Guía BASICA', 'Beacons', '2025-03-11', 'beacons'),
('soymelisavargas5@gmail.com', 'Silvia', 'Vargas', 'Store - Guía BASICA', 'Beacons', '2025-03-10', 'beacons'),
('dannifelserrapas@gmail.com', 'Daniel', 'Serrano', 'Store - Guía BASICA', 'TikTok', '2025-03-10', 'beacons'),
('isaac.corredor1002@gmail.com', 'Isaac', NULL, 'Store - Guía BASICA', 'TikTok', '2025-03-10', 'beacons'),
('eltatosilva02@gmail.com', 'David', 'Silva', 'Store - Guía BASICA', 'TikTok', '2025-03-10', 'beacons');

-- Verificar cuántos registros tenemos ahora
SELECT 
  imported_from,
  COUNT(*) as total,
  MIN(date_added) as earliest,
  MAX(date_added) as latest
FROM newsletter_subscribers 
GROUP BY imported_from;
